# Generated by Django 5.2.7 on 2025-10-12 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название группы')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО студента')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.group', verbose_name='Группа')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата занятия')),
                ('present', models.BooleanField(default=True, verbose_name='Присутствовал')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.student', verbose_name='Студент')),
            ],
        ),
    ]
