# Generated by Django 5.2.7 on 2025-12-08 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='name',
            field=models.CharField(default=1, max_length=100, verbose_name='ФИО преподователя'),
            preserve_default=False,
        ),
    ]
